version: "1"

capabilities:
  - contract_id: "createalbum"
  - contract_id: "getalbums"
  - contract_id: "getalbumbyid"
  - contract_id: "updatealbum"
  - contract_id: "deletealbum"

  - contract_id: "abesh:httpserver2"
    values:
      host: "0.0.0.0"
      port: "8080"
      default_request_timeout: "5s"

triggers:
  - trigger: "abesh:httpserver2"
    trigger_values:
      method: "POST"
      path: "/create/album"
    service: "createalbum"

  - trigger: "abesh:httpserver2"
    trigger_values:
      method: "GET"
      path: "/albums"
    service: "getalbums"

  - trigger: "abesh:httpserver2"
    trigger_values:
      method: "GET"
      path: "/album/:id"
    service: "getalbumbyid"

  - trigger: "abesh:httpserver2"
    trigger_values:
      method: "PUT"
      path: "/update/album"
    service: "updatealbum"

  - trigger: "abesh:httpserver2"
    trigger_values:
      method: "DELETE"
      path: "/album/:id"
    service: "deletealbum"

start:
  - "abesh:httpserver2"
